fastlane_version "2.89.0"

default_platform :ios

platform :ios do

  desc "Release a new version of CodableStoreKit"
  lane :release do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    test
    version = options[:version]
    increment(version: version)
    add_git_tag(tag: version)
    push_git_tags()
    push_to_git_remote()
    pod_push()
  end

  desc "Increment Version"
    lane :increment do |options|
    version = options[:version]
    version_bump_podspec(
      path: "CodableStoreKit.podspec", 
      version_number: version
    )
    set_info_plist_value(
      path: "Configs/CodableStoreKit.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    set_info_plist_value(
      path: "Configs/CodableStoreKit.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    set_info_plist_value(
      path: "Example/Resources/Info.plist", 
      key: "CFBundleShortVersionString", 
      value: version
    )
    git_commit(
        path: [
          "CodableStoreKit.podspec", 
          "Configs/CodableStoreKit.plist", 
          "Configs/CodableStoreKit.plist", 
          "Example/Resources/Info.plist"
        ],
        message: "CodableStoreKit Version #{version} 🚀"
    )
  end

  desc "Runs Tests"
  lane :test do
    carthage(command: "build", no_skip_current: true, cache_builds: true)
    #pod_lib_lint
    scan(
      project: "CodableStoreKit.xcodeproj",
      scheme: "CodableStoreKit-iOS",
      clean: true,
      code_coverage: true
    )
    scan(
      project: "CodableStoreKit.xcodeproj",
      scheme: "CodableStoreKit-tvOS",
      clean: true,
      code_coverage: true
    )
    scan(
      project: "CodableStoreKit.xcodeproj",
      scheme: "CodableStoreKit-macOS",
      clean: true,
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    slather(
      proj: "CodableStoreKit.xcodeproj",
      scheme: "CodableStoreKit-iOS",
      travis: true,
      cobertura_xml: true,
      ignore: ["Tests/*"]
    )
  end

end
